# main.yml
# https://github.com/marketplace/actions/flutter-action
# https://github.com/marketplace/actions/create-release
# 工作流程的名字
name: Build and Release apk

# 工作流程触发的时机，这里是当一个版本标签推送到仓库时触发
on:
  push:
    tags:
      - v*

# 这个工作流程需要执行的任务
jobs:
  process:
    name: all process
    runs-on: ubuntu-latest
    # 这个任务的步骤
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'dev' or 'beta'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --release --no-tree-shake-icons
      - uses: actions/upload-artifact@v2
        with:
          path: build/app/outputs/apk/release/*.apk
      - run: |
          curl -F "file=@build/app/outputs/apk/release/app-release.apk" -F "uKey=${{ secrets.PGY_USER_KEY }}" -F "_api_key=${{ secrets.PGY_API_KEY }}" https://upload.pgyer.com/apiv1/app/upload